#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

while :
do
   case $1 in
   --debug)
      debug="true"
      shift
      ;;
   --non-interactive)
      continue_debug="y"
      shift
      ;;
   --vm)
      kernel_config="hardened-vm-kernel"
      shift
      ;;
   --host)
      kernel_config="hardened-host-kernel"
      shift
      ;;
   --)
      shift
      break
      ;;
   -*)
      echo "ERROR: Not a valid option." >&2
      exit 1
      ;;
   *)
      break
      ;;
   esac
done

if [ "$kernel_config" = "" ]; then
   echo "ERROR: You need to add either --vm or --host parameter." >&2
   exit 1
fi

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## example MYDIR:
## /usr/share/hardened-kernel

## example MYDIR:
## /home/travis/build/Whonix/hardened-kernel/usr/share/hardened-kernel

## Debugging.
whoami
env

if [ "$CI" = "true" ]; then
   sudo_tool="sudo --non-interactive"
else
   sudo_tool="sudo"
fi

version="4.19.93"

## Location similar to DKMS.
## DKMS uses /var/lib/dkms/lkrg/build/.
working_folder="/var/lib/hardened-kernel/${kernel_config}"
rm -r -f "$working_folder"
mkdir -p "$working_folder"
chmod o-rwx "$working_folder"

source_folder="${working_folder}/linux-${version}/"

kernel_source="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${version}.tar.xz"
linux_hardened_patch="https://github.com/anthraxx/linux-hardened/releases/download/${version}.a/linux-hardened-${version}.a.patch"

curl_opts="--tlsv1.2 --proto =https --location --remote-name-all --remote-header-name"

## TODO: do not use networking as per https://forums.whonix.org/t/kernel-recompilation-for-better-hardening/7598/214
curl $curl_opts "${kernel_source}" -o "${working_folder}/linux-${version}.tar.xz"
curl $curl_opts "${linux_hardened_patch}" -o "${working_folder}/linux-hardened-${version}.a.patch"

tar -xf "${working_folder}/linux-${version}.tar.xz" -C "$working_folder"

## Debugging.
ls "$working_folder"
ls "$source_folder"

cat "${working_folder}/linux-hardened-${version}.a.patch" | patch --silent -p1 -d "$source_folder"

cp "${MYDIR}/${kernel_config}" "$source_folder/.config"

## Sanity test.
diff "${MYDIR}/${kernel_config}" "$source_folder/.config"

if [ "$debug" = "true" ]; then
   if [ "${continue_debug,,}" = "y" ]; then
      true
   else
      ## read requires stdin. Otherwise would fail if stdin is not connected.
      read -r -p "WARNING: You have configured to build your kernel with debugging enabled. This can severely worsen security. Continue? (y/n) " continue_debug
      if [ ! "${continue_debug,,}" = "y" ]; then
         echo "You have selected to not continue. Exiting."
         exit
      fi
   fi

   cat "${MYDIR}/debugging-config" >> "$source_folder/.config"
   make oldconfig -C "$source_folder"
fi

make deb-pkg -j "$(($(nproc) + 1))" -C "$source_folder"

## Debugging.
ls "$working_folder"
