#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## Debugging.
whoami
env

if [ "$CI" = "true" ]; then
   sudo_tool="sudo --non-interactive"
else
   sudo_tool="sudo"
fi

## TODO: This probably has to be converted to debian/control 'Depends:'.
$sudo_tool apt-get --no-install-recommends --yes install build-essential libssl-dev libncurses-dev fakeroot libelf-dev bison flex gcc-8-plugin-dev curl bc kmod cpio

version="4.19.93"

## TODO: Probably better using mktemp?
working_folder=~/kernel

source_folder="${working_folder}/linux-${version}/"

kernel_source="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${version}.tar.xz"
linux_hardened_patch="https://github.com/anthraxx/linux-hardened/releases/download/${version}.a/linux-hardened-${version}.a.patch"

## TODO: Wipe existing working_folder?

## TODO: working_folder permissions

mkdir -p "$working_folder"

curl_opts="--tlsv1.2 --proto =https --location --remote-name-all --remote-header-name"

## TODO: do not use networking as per https://forums.whonix.org/t/kernel-recompilation-for-better-hardening/7598/214
curl $curl_opts "${kernel_source}" -o "${working_folder}/linux-${version}.tar.xz"
curl $curl_opts "${linux_hardened_patch}" -o "${working_folder}/linux-hardened-${version}.a.patch"

tar -xf "${working_folder}/linux-${version}.tar.xz" -C "$working_folder"

## Debugging.
ls "$working_folder"
ls "$source_folder"

cat "${working_folder}/linux-hardened-${version}.a.patch" | patch --silent -p1 -d "$source_folder"

## TODO: do not hardcode and add support for hardened-host-kernel
kernel_config="hardened-vm-kernel"

cp "${MYDIR}/${kernel_config}" "$source_folder/.config"

## Sanity test.
diff "${MYDIR}/${kernel_config}" "$source_folder/.config"

make deb-pkg -j "$(($(nproc) + 1))" -C "$source_folder"

## Debugging.
ls "$working_folder"
