#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## travis.debian.net does not pass the CI environment variable to docker.
CI=true
export CI

apt-get update

## Sanity tests.
apt-get --yes dist-upgrade
dpkg --configure -a

apt-get --yes install sudo virt-what

## Debugging.
systemd-detect-virt || true
virt-what || true
pwd || true
true "TRAVIS_DEBIAN_TARGET_DIR: $TRAVIS_DEBIAN_TARGET_DIR"
ls "$TRAVIS_DEBIAN_TARGET_DIR" || true

"${MYDIR}/build"

true "INFO: ${MYDIR}/build success.
