#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

true "$0: start"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## travis.debian.net does not pass the CI environment variable to docker.
CI=true
export CI

apt-get update

## Sanity tests.
apt-get --yes dist-upgrade
dpkg --configure -a

apt-get --yes install sudo virt-what

## Debugging.
#systemd-detect-virt || true
virt-what || true
pwd_output="$(pwd)" || true
ls "$pwd_output" || true

## The environment variables are not set here.
#true "$0: TRAVIS_DEBIAN_BUILD_DIR: $TRAVIS_DEBIAN_BUILD_DIR"
#true "$0: TRAVIS_DEBIAN_TARGET_DIR: $TRAVIS_DEBIAN_TARGET_DIR"

"${MYDIR}/build" --vm --debug --non-interactive

true "$0 INFO: ${MYDIR}/build success."

## TODO: do not hardcode hardened-vm-kernel

## Debugging.
find /var/lib/hardened-kernel/hardened-vm-kernel -type f -maxdepth 1

true "$0 INFO: OK."

## Move to /home/travis/build/ so travis.debian.net script can copy it out of
## the docker container.
## XXX: using find in for might not be safe but good enough for CI.
for file_name in $(find /var/lib/hardened-kernel/hardened-vm-kernel -type f -maxdepth 1) ; do
   mv "$file_name" /home/travis/build/
done

## Debugging.
ls "/home/travis/build/" || true

## Try install newly built kernel.
dpkg -i "/home/travis/build/"*".deb" || true

true "$0 INFO: OK. End."
