#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## TODO: This probably has to be converted to debian/control 'Depends:'.
sudo apt-get --no-install-recommends --yes install build-essential libssl-dev libncurses-dev fakeroot libelf-dev bison flex gcc-8-plugin-dev

version="4.19.91"

## TODO: Probably better using mktemp?
working_folder=~/kernel

source_folder="${working_folder}/linux-${version}/"

kernel_source="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${version}.tar.xz"
linux_hardened_patch="https://github.com/anthraxx/linux-hardened/releases/download/${version}.a/linux-hardened-${version}.a.patch"

## TODO: Wipe existing working_folder?

## TODO: working_folder permissions

mkdir -p "$working_folder"

if [ "$CI" = "true" ]; then
   ## TODO: Do not hardcode path to Linux source archive on CI.
   tar -xaf "/usr/src/linux-source-4.15.0.tar.bz2" -C "$working_folder"
else
   scurl-download "${kernel_source}" -o "${working_folder}/linux-${version}.tar.xz"
   scurl-download "${linux_hardened_patch}" -o "${working_folder}/linux-hardened-${version}.a.patch"
   tar -xf "${working_folder}/linux-${version}.tar.xz" -C "${source_folder}"
   cat "${working_folder}/linux-hardened-${version}.a.patch" | patch --silent -p1 -d "$source_folder"
fi

cp "${MYDIR}/kernel-config" "$source_folder/.config"

## Sanity test.
diff "${MYDIR}/kernel-config" "$source_folder/.config"

make deb-pkg -j "$(nproc)" -C "$source_folder"
