#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

## TODO: This probably has to be converted to debian/control 'Depends:'.
sudo apt-get --no-install-recommends --yes install linux-source build-essential libssl-dev libncurses-dev fakeroot libelf-dev bison flex gcc-8-plugin-dev

linux_source_depends="$(dpkg-query --show --showformat='${depends}' "linux-source")"
## example linux_source_depends:
## linux-source-4.19

remove_string="linux-source-"

version="${linux_source_depends##$remove_string}"

## example version:
## 4.19

## TODO: Probably better using mktemp?
working_folder=~/kernel

source_folder="${working_folder}/linux-source-${version}/"

## TODO: Wipe existing working_folder?

## TODO: working_folder permissions

mkdir -p "$working_folder"

tar -xaf "/usr/src/linux-source-${version}.tar.xz" -C "$working_folder"

xzcat "/usr/src/linux-patch-${version}-rt.patch.xz" | patch --silent -p1 -d "$source_folder"

## TODO: path to .config
cp usr/share/hardened-vm-kernel/kernel-config "$source_folder/.config"

make deb-pkg -j $(nproc) -C "$source_folder"
