#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## TODO: This probably has to be converted to debian/control 'Depends:'.
sudo apt-get --no-install-recommends --yes install linux-source build-essential libssl-dev libncurses-dev fakeroot libelf-dev bison flex gcc-8-plugin-dev

linux_source_depends="$(dpkg-query --show --showformat='${depends}' "linux-source")"
## example linux_source_depends:
## linux-source-4.19

remove_string="linux-source-"

version="${linux_source_depends##$remove_string}"

## example version:
## 4.19

## TODO: Probably better using mktemp?
working_folder=~/kernel

source_folder="${working_folder}/linux-source-${version}/"

## TODO: Wipe existing working_folder?

## TODO: working_folder permissions

mkdir -p "$working_folder"

if [ "$CI" = "true" ]; then
   ## TODO: Do not hardcode path to Linux source archive on CI.
   tar -xaf "/usr/src/linux-source-4.15.0.tar.bz2" -C "$working_folder"
else
   ## Debian buster:
   ## /usr/src/linux-source-4.19.tar.xz
   tar -xaf "/usr/src/linux-source-${version}.tar.xz" -C "$working_folder"
   xzcat "/usr/src/linux-patch-${version}-rt.patch.xz" | patch --silent -p1 -d "$source_folder"
fi

cp "${MYDIR}/kernel-config" "$source_folder/.config"

## Sanity test.
diff "${MYDIR}/kernel-config" "$source_folder/.config"

make deb-pkg -j "$(($(nproc) + 1))" -C "$source_folder"
